#!/usr/bin/env python
'''
Patterns represented as matrices
Ben Soh
'''

UNKNOWN = 0
PINK = 1
GREEN = 2

PATTERN_0 = ((PINK, PINK), (GREEN, PINK))
PATTERN_1 = ((GREEN, PINK), (GREEN, PINK))
PATTERN_2 = ((GREEN, GREEN), (GREEN, PINK))
PATTERN_3 = ((PINK, GREEN), (GREEN, PINK))
PATTERN_4 = ((PINK, PINK), (PINK, GREEN))
PATTERN_5 = ((GREEN, PINK), (PINK, GREEN))
PATTERN_6 = ((GREEN, GREEN), (PINK, GREEN))
PATTERN_7 = ((PINK, GREEN), (PINK, GREEN))
PATTERN_8 = ((GREEN, GREEN), (GREEN, GREEN))
PATTERN_9 = ((PINK, PINK), (PINK, PINK))
PATTERN_10 = ((PINK, PINK), (GREEN, GREEN))
PATTERN_11 = ((GREEN, GREEN), (PINK, PINK))

PATTERNS = {}
PATTERNS[PATTERN_0] = 0
PATTERNS[PATTERN_1] = 1
PATTERNS[PATTERN_2] = 2
PATTERNS[PATTERN_3] = 3
PATTERNS[PATTERN_4] = 4
PATTERNS[PATTERN_5] = 5
PATTERNS[PATTERN_6] = 6
PATTERNS[PATTERN_7] = 7
PATTERNS[PATTERN_8] = 8
PATTERNS[PATTERN_9] = 9
PATTERNS[PATTERN_10] = 10
PATTERNS[PATTERN_11] = 11
